### ISSUE TITLE
try locking maps

### ISSUE THREAD

**Issue by lprimak** [Pandrex247/clustered-singleton#1]
See https://docs.hazelcast.com/hazelcast/5.3/data-structures/locking-maps
In addition to locking the FencedLock, lock map as well.
I am just guessing here but maybe multiple threads are overwriting each other in hazelcast itself,
since map updates are synchronous.

**Comment by lprimak** [comment]
never mind... don't want to send you on the wrong track.
Map updates are synchronous (with `put()`) and that shouldn't cause a race since put() is called from within state that's locked via the distributed lock

**Comment by Pandrex247** [comment]
I was just saving this reproducer somewhere :)
This isn't an actual project I'm working on 😜
